name: Deploy to GCP Instance Group

on:
  workflow_run:
    workflows: [ "integration" ]
    branches: [ "main" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_JSON_KEY }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and upload artifacts
        run: |
          ./gradlew build
          gsutil cp -r build gs://$GCS_BUCKET_NAME

        env:
          GCS_BUCKET_NAME: 'itjobs-bucket'

      - name: Deploy to GCP
        run: |
          gcloud compute instance-groups managed rolling-action start-update $INSTANCE_GROUP_NAME --version template=$INSTANCE_TEMPLATE_NAME --zone $ZONE
        env:
          INSTANCE_GROUP_NAME: 'instance-group-2'
          INSTANCE_TEMPLATE_NAME: 'instance-template-20240225-082602'
          ZONE: 'asia-northeast3-a'